const videos = [
    {
        'id': 1,
        'url': 'https://firebasestorage.googleapis.com/v0/b/fir-5612c.appspot.com/o/videos%2F24kGoldn%20-%20Mood%20(Official%20Video)%20ft.%20iann%20dior.mp4?alt=media&token=e11eb1d7-adac-4a1a-b340-0deae29e91e5',
        'title': '24kGoldn - Mood (Official Video) ft. iann dior',
        'duration': '02:30',
        'author': 'Star Milo',
        'authorID': 'mDZqi6TreFYJY5KHILHJ',
        'descriprion': ' All led out world these music while asked. Paid mind even sons does he door no. Attended overcame repeated it is perceive marianne in. In am think on style child of. Servants moreover in sensible he it ye possible.',
        'views': 191968,
        'likes': 325246,
        'dislikes': 32432,
        'isLikedBy': [],
        'isDislikedBy': [],
        'isWatchedBy': []
    },
    {
        'url': 'https://firebasestorage.googleapis.com/v0/b/fir-5612c.appspot.com/o/videos%2FAvicii%20-%20Wake%20Me%20Up%20(Official%20Video).mp4?alt=media&token=d0047280-04cf-4964-af6c-15dd8d300da0',
        'title': 'Avicii - Wake Me Up (Official Video)',
        'duration': '04:32',
        'authorID': 'aRC3d7hNUE1lhZIInmPH',
        'author': 'Jackson Emmy',
        'descriprion': ' Are dear but near left was. Year kept on over so as this of. She steepest doubtful betrayed formerly him. Active one called uneasy our seeing see cousin tastes its. Ye am it formed indeed agreed relied piqued. ',
        'views': 236347,
        'likes': 225,
        'dislikes': 994,
        'isLikedBy': [],
        'isDislikedBy': [],
        'isWatchedBy': []
    },
    {
        'url': 'https://firebasestorage.googleapis.com/v0/b/fir-5612c.appspot.com/o/videos%2FDeep%20Emotions%202021%20Deep%20House%20Nu%20Disco%20Chill%20House%20Mix.mp4?alt=media&token=b538c0de-ffda-42f5-ac3e-1131447af888',
        'title': 'Deep Emotions 2021 Deep House Nu Disco Chill House Mix',
        'duration': '1:00:54',
        'authorId': '13511zf61vvoEDWiAqTU',
        'author': 'Githa Adrianna',
        'descriprion': 'An course regard to up he hardly. View four has said does men saw find dear shy. Talent men wicket add garden. ',
        'views': 3634,
        'likes': 235,
        'dislikes': 325,
        'isLikedBy': [],
        'isDislikedBy': [],
        'isWatchedBy': []
    },
    {
        'url': 'https://firebasestorage.googleapis.com/v0/b/fir-5612c.appspot.com/o/videos%2FDynoro%20%26%20Fumaratto%20-%20Me%20Provocas%20(Official%20Video).mp4?alt=media&token=005c22f7-b468-4a32-8f93-f4ac82314ff5',
        'title': 'Dynoro & Fumaratto - Me Provocas (Official Video)',
        'duration': '02:27',
        'author': 'Star Milo',
        'authorID': 'mDZqi6TreFYJY5KHILHJ',
        'descriprion': ' All led out world these music while asked. Paid mind even sons does he door no. Attended overcame repeated it is perceive marianne in. In am think on style child of. Servants moreover in sensible he it ye possible.',
        'views': 643632,
        'likes': 4657,
        'dislikes': 2143,
        'isLikedBy': [],
        'isDislikedBy': [],
        'isWatchedBy': []
    },
    {
        'url': 'https://firebasestorage.googleapis.com/v0/b/fir-5612c.appspot.com/o/videos%2FImagine%20Dragons%20-%20Whatever%20It%20Takes%20(Lyrics%20Lyric%20Video).mp4?alt=media&token=a05817f6-b426-4400-abbe-918f83b74094',
        'title': 'Imagine Dragons - Whatever It Takes (Lyrics Lyric Video)',
        'duration': '03:22',
        'authorID': 'aRC3d7hNUE1lhZIInmPH',
        'author': 'Jackson Emmy',
        'descriprion': ' Are dear but near left was. Year kept on over so as this of. She steepest doubtful betrayed formerly him. Active one called uneasy our seeing see cousin tastes its. Ye am it formed indeed agreed relied piqued. ',
        'views': 3565754,
        'likes': 12345,
        'dislikes': 2144,
        'isLikedBy': [],
        'isDislikedBy': [],
        'isWatchedBy': []
    },
    {
        'url': 'https://firebasestorage.googleapis.com/v0/b/fir-5612c.appspot.com/o/videos%2FJoel%20Corry%20x%20MNEK%20-%20Head%20%26%20Heart%20%5BOfficial%20Video%5D.mp4?alt=media&token=cecc0c7b-b5a5-4af5-847d-f42693c0daa3',
        'title': 'Joel Corry x MNEK - Head & Heart',
        'duration': '02:47',
        'authorId': '13511zf61vvoEDWiAqTU',
        'author': 'Githa Adrianna',
        'descriprion': 'An course regard to up he hardly. View four has said does men saw find dear shy. Talent men wicket add garden. ',
        'views': 3843634,
        'likes': 2435,
        'dislikes': 3235,
        'isLikedBy': [],
        'isDislikedBy': [],
        'isWatchedBy': []
    },
    {
        'url': 'https://firebasestorage.googleapis.com/v0/b/fir-5612c.appspot.com/o/videos%2FKonfuz%20%D0%A0%D0%B0%D1%82%D0%B0%D1%82%D0%B0Ratatatata%20(Robert%20Cristian%20Remix).mp4?alt=media&token=467c802d-45c1-4db6-a0f1-331ff70d9cee',
        'title': 'Konfuz РататаRatatatata (Robert Cristian Remix)',
        'duration': '02:31',
        'author': 'Star Milo',
        'authorID': 'mDZqi6TreFYJY5KHILHJ',
        'descriprion': ' All led out world these music while asked. Paid mind even sons does he door no. Attended overcame repeated it is perceive marianne in. In am think on style child of. Servants moreover in sensible he it ye possible.',
        'views': 2343,
        'likes': 57568,
        'dislikes': 124,
        'isLikedBy': [],
        'isDislikedBy': [],
        'isWatchedBy': []
    },
    {
        'url': 'https://firebasestorage.googleapis.com/v0/b/fir-5612c.appspot.com/o/videos%2FMaroon%205%20-%20Memories%20(Official%20Video).mp4?alt=media&token=dbd17bfa-8211-4928-8700-f463bfc47e7c',
        'title': 'Maroon 5 - Memories',
        'duration': '03:15',
        'authorID': 'aRC3d7hNUE1lhZIInmPH',
        'author': 'Jackson Emmy',
        'descriprion': ' Are dear but near left was. Year kept on over so as this of. She steepest doubtful betrayed formerly him. Active one called uneasy our seeing see cousin tastes its. Ye am it formed indeed agreed relied piqued. ',
        'views': 236347,
        'likes': 2425,
        'dislikes': 9394,
        'isLikedBy': [],
        'isDislikedBy': [],
        'isWatchedBy': []
    },
    {
        'url': 'https://firebasestorage.googleapis.com/v0/b/fir-5612c.appspot.com/o/videos%2FMartin%20Garrix%20-%20Forbidden%20Voices%20(Official%20Music%20Video).mp4?alt=media&token=ccd23fa1-2c3f-4f7d-9b7e-2913a53ae138',
        'title': 'Martin Garrix - Forbidden Voices',
        'duration': '03:30',
        'authorId': '13511zf61vvoEDWiAqTU',
        'author': 'Githa Adrianna',
        'descriprion': 'An course regard to up he hardly. View four has said does men saw find dear shy. Talent men wicket add garden. ',
        'views': 33634,
        'likes': 243,
        'dislikes': 335,
        'isLikedBy': [],
        'isDislikedBy': [],
        'isWatchedBy': []
    },
    {
        'url': 'https://firebasestorage.googleapis.com/v0/b/fir-5612c.appspot.com/o/videos%2FMascota%20-%20Autumn-Winter%20Fashion%202020.mp4?alt=media&token=84216897-3162-4f66-ac3a-cb51112f1f61',
        'title': 'Mascota - Autumn-Winter Fashion 2020',
        'duration': '1:11:41',
        'author': 'Star Milo',
        'authorID': 'mDZqi6TreFYJY5KHILHJ',
        'descriprion': ' All led out world these music while asked. Paid mind even sons does he door no. Attended overcame repeated it is perceive marianne in. In am think on style child of. Servants moreover in sensible he it ye possible.',
        'views': 191668,
        'likes': 36,
        'dislikes': 432,
        'isLikedBy': [],
        'isDislikedBy': [],
        'isWatchedBy': []
    },
    {
        'url': 'https://firebasestorage.googleapis.com/v0/b/fir-5612c.appspot.com/o/videos%2FMiley%20Cyrus%20-%20Prisoner%20(Official%20Video)%20ft.%20Dua%20Lipa.mp4?alt=media&token=9e34f39d-b987-4d44-b61e-cd9cb8a69449',
        'title': 'Miley Cyrus - Prisoner (Official Video) ft. Dua Lipa',
        'duration': '03:14',
        'authorID': 'aRC3d7hNUE1lhZIInmPH',
        'author': 'Jackson Emmy',
        'descriprion': ' Are dear but near left was. Year kept on over so as this of. She steepest doubtful betrayed formerly him. Active one called uneasy our seeing see cousin tastes its. Ye am it formed indeed agreed relied piqued. ',
        'views': 236347,
        'likes': 2425,
        'dislikes': 9394,
        'isLikedBy': [],
        'isDislikedBy': [],
        'isWatchedBy': []
    },
    {
        'url': 'https://firebasestorage.googleapis.com/v0/b/fir-5612c.appspot.com/o/videos%2FSAINt%20JHN%20-%20ROSES%20(Imanbek%20Remix).mp4?alt=media&token=99419eff-3fdc-4d7f-ab77-04558db0e9ab',
        'title': 'SAINt JHN - ROSES (Imanbek Remix)',
        'duration': '02:57',
        'authorId': '13511zf61vvoEDWiAqTU',
        'author': 'Githa Adrianna',
        'descriprion': 'An course regard to up he hardly. View four has said does men saw find dear shy. Talent men wicket add garden. ',
        'views': 43634,
        'likes': 32546,
        'dislikes': 1245,
        'isLikedBy': [],
        'isDislikedBy': [],
        'isWatchedBy': []
    },
    {
        'url': 'https://firebasestorage.googleapis.com/v0/b/fir-5612c.appspot.com/o/videos%2FTONES%20AND%20I%20-%20DANCE%20MONKEY%20(OFFICIAL%20VIDEO).mp4?alt=media&token=5d12a64b-99c2-4ea7-a403-16379b76feaa',
        'title': 'TONES AND I - DANCE MONKEY',
        'duration': '03:56',
        'author': 'Star Milo',
        'authorID': 'mDZqi6TreFYJY5KHILHJ',
        'descriprion': ' All led out world these music while asked. Paid mind even sons does he door no. Attended overcame repeated it is perceive marianne in. In am think on style child of. Servants moreover in sensible he it ye possible.',
        'views': 19668,
        'likes': 346,
        'dislikes': 332,
        'isLikedBy': [],
        'isDislikedBy': [],
        'isWatchedBy': []
    },
    {
        'url': 'https://firebasestorage.googleapis.com/v0/b/fir-5612c.appspot.com/o/videos%2FTake%20Me%20To%20Church%20-%20Hozier%20(Lyrics).mp4?alt=media&token=9287176e-7d64-4c13-9340-ebdcd8f0506a',
        'title': 'Take Me To Church - Hozier',
        'duration': '04:49',
        'authorID': 'aRC3d7hNUE1lhZIInmPH',
        'author': 'Jackson Emmy',
        'descriprion': ' Are dear but near left was. Year kept on over so as this of. She steepest doubtful betrayed formerly him. Active one called uneasy our seeing see cousin tastes its. Ye am it formed indeed agreed relied piqued. ',
        'views': 6347,
        'likes': 425,
        'dislikes': 994,
        'isLikedBy': [],
        'isDislikedBy': [],
        'isWatchedBy': []
    },
    {
        'url': 'https://firebasestorage.googleapis.com/v0/b/fir-5612c.appspot.com/o/videos%2FTopic%2C%20A7S%20-%20Breaking%20Me%20ft.%20A7S.mp4?alt=media&token=08b60369-1e8d-44c0-97a8-f4d1533bf69e',
        'title': 'Topic, A7S - Breaking Me ft. A7S',
        'duration': '02:46',
        'authorId': '13511zf61vvoEDWiAqTU',
        'author': 'Githa Adrianna',
        'descriprion': 'An course regard to up he hardly. View four has said does men saw find dear shy. Talent men wicket add garden. ',
        'views': 3843634,
        'likes': 2435,
        'dislikes': 3235,
        'isLikedBy': [],
        'isDislikedBy': [],
        'isWatchedBy': []
    },
    {
        'url': 'https://firebasestorage.googleapis.com/v0/b/fir-5612c.appspot.com/o/videos%2F%D0%A7%D0%B5%D1%80%D0%B2%D0%B5%D0%BD%D0%B0%D1%82%D0%B0%20%D1%88%D0%B0%D0%BF%D1%87%D0%B8%D1%86%D0%B0%20-%20%D0%B4%D0%B5%D1%82%D1%81%D0%BA%D0%B0%20%D0%BF%D0%B5%D1%81%D0%BD%D0%B8%D1%87%D0%BA%D0%B0.mp4?alt=media&token=5c44f1af-e2b1-4119-81d2-e824eebd87e7',
        'title': 'Червената шапчица - детска песничка',
        'duration': '02:15',
        'authorId': '13511zf61vvoEDWiAqTU',
        'author': 'Githa Adrianna',
        'descriprion': 'An course regard to up he hardly. View four has said does men saw find dear shy. Talent men wicket add garden. ',
        'views': 0,
        'likes': 0,
        'dislikes': 0,
        'isLikedBy': [],
        'isDislikedBy': [],
        'isWatched': []
    }
]